---
  kind: "Template"
  apiVersion: "v1"
  metadata:
    name: "cara-route"
    creationTimestamp: null
    annotations:
      description: "CARA route OpenShift template."
      tags: "cara-route"
  labels:
    template: "cara-route"
  objects:
    -
      apiVersion: v1
      kind: Route
      metadata:
        name: cara-route
        labels:
          app: "cara-route"
      spec:
        host: ${HOST}
        port:
          targetPort: 8080-tcp
        tls:
          insecureEdgeTerminationPolicy: Redirect
          termination: edge
        to:
          kind: Service
          name: cara-router
          weight: 100
        wildcardPolicy: None

  parameters:
    - name: HOST
      description: The hostname of the site, e.g. test-cara.web.cern.ch
      required: true

